<a href="https://colab.research.google.com/github/IvanCampos11/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [0]:
# YOUR WORK HERE
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-09 22:18:50--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.1’

student.zip.1       100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-06-09 22:18:50 (311 KB/s) - ‘student.zip.1’ saved [20478/20478]



In [0]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-mat.csv         
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: a
error:  invalid response [a]
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [0]:
import pandas as pd
import numpy as np
from scipy import stats

In [0]:
df = pd.read_csv("student-mat.csv", sep=';')

In [58]:
df

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1       GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2       GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3       GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4       GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8   9   9

[395 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [0]:
# YOUR WORK HERE
contingency = pd.crosstab(df['traveltime'], df['failures'])

In [60]:
contingency

failures      0   1  2   3
traveltime                
1           209  30  7  11
2            80  17  9   1
3            17   3  1   2
4             6   0  0   2

In [61]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 21.124872298979813
p value 0.012107363244231761
degrees of freedom 9
expected frequencies table [[202.99746835  32.53164557  11.06075949  10.41012658]
 [ 84.5164557   13.5443038    4.60506329   4.33417722]
 [ 18.16708861   2.91139241   0.98987342   0.93164557]
 [  6.31898734   1.01265823   0.3443038    0.32405063]]


In [0]:
contingency2 = pd.crosstab(df['activities'], df['nursery'])

In [63]:
contingency2

nursery     no  yes
activities         
no          40  154
yes         41  160

In [64]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency2)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 0.004951472553918086
p value 0.9439017945961875
degrees of freedom 1
expected frequencies table [[ 39.78227848 154.21772152]
 [ 41.21772152 159.78227848]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [65]:
# YOUR WORK HERE
observed = pd.crosstab(df['traveltime'], df['failures'])
observed

failures      0   1  2   3
traveltime                
1           209  30  7  11
2            80  17  9   1
3            17   3  1   2
4             6   0  0   2

In [66]:
observed_with_margins = pd.crosstab(df['sex'], df['internet'], margins=True)

observed_with_margins

internet  no  yes  All
sex                   
F         38  170  208
M         28  159  187
All       66  329  395

In [67]:
observed = observed.values
observed

array([[209,  30,   7,  11],
       [ 80,  17,   9,   1],
       [ 17,   3,   1,   2],
       [  6,   0,   0,   2]])

In [45]:
row_totals = observed_with_margins.iloc[2:4, 0:2].values[0]

row_totals

array([ 66, 329])

In [46]:
col_totals = observed_with_margins.iloc[0:2, 2:3].values.T[0]

col_totals

array([208, 187])

In [47]:
sample_size = df.shape[0]

sample_size

395

In [51]:
expected = np.array([[0,0],
                     [0,0]])

for i, col in enumerate(col_totals):
  for j, row in enumerate(row_totals): 
    expected_value = (row*col / sample_size)
    expected[i][j] = expected_value

expected

array([[ 34, 173],
       [ 31, 155]])

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)